name: Assessment CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Snyk Security Scan
      uses: snyk/actions/python@master
      with:
        command: code test --sarif
        args: --sarif-file-output=snyk_code_test.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: Run Snyk monitor
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
      
    - name: Create SARIF directory and move SARIF files
      run: |
        mkdir sarif_files &&
        mv snyk_test.sarif snyk_code_test.sarif sarif_files/
      
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: sarif_files
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: login to docker registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: build and push docker image to registry
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: harshitsengar/demo-app-1:latest
