name: Assessment CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node
      uses: actions/setup-node@v4

    - name: Snyk Security Scan
      uses: snyk/actions/node@master
      with:
        command: code test --sarif
        args: --sarif-file-output=snyk_code_test.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: Run Snyk monitor
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: login to docker registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: build and push docker image to registry
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: harshitsengar/demo-app-2:latest
