name: Assessment CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Snyk CLI
      run: pip install snyk
      
    - name: Snyk Security Scan
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN

    - name: Run Snyk SAST Scan
      run: snyk test --file=requirements.txt --dev
    
    - name: Snyk Report
      run: snyk monitor --all-projects --json | snyk-to-html -o snyk_report.html

    - name: Upload Snyk Report
      uses: actions/upload-artifact@v2
      with:
        name: snyk-report
        path: snyk_report.html
    
    - name: login to docker registry
      uses: docker/login-action@v3
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
          
    - name: build and push docker image to registry
      uses: docker/build-push-action@v5
      with:
        context: DockerFileFolder/
        push: true
        tags: harshitsengar/demo-app-1:latest
